// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qafwvldnxwyionfaveil.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhZnd2bGRueHd5aW9uZmF2ZWlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NTEzMDAsImV4cCI6MjA3MDQyNzMwMH0.Bi4HpZZil_xzfyBemRbcceUhZrzK3GW4bIuMLprjk_I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});